/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AsEscuras.Layout;

import AsEscuras.Algoritimo.Escolhas;
import java.awt.event.KeyEvent;

/**
 *
 * @author GregoryGorzizadosSan
 */
public class F_Home extends javax.swing.JFrame {
    int id = 0;
    int atracao = 0;
    String nome = "";
    int gostei = 0;
    int amei = 0; 
    /**
     * Creates new form F_Cadastro_Cliente
     */   
    public F_Home() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        bg_documento = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        painel_fundo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bt_perfil = new javax.swing.JLabel();
        bt_voltar = new javax.swing.JLabel();
        bt_encontro = new javax.swing.JLabel();
        painel_container = new javax.swing.JPanel();
        imagem_list = new javax.swing.JLabel();

        jColorChooser1.setBackground(new java.awt.Color(0, 0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));

        painel_fundo.setBackground(new java.awt.Color(153, 153, 153));
        painel_fundo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painel_fundo.setPreferredSize(new java.awt.Dimension(360, 720));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(360, 100));

        bt_perfil.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        bt_perfil.setForeground(new java.awt.Color(255, 255, 255));
        bt_perfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_perfil.setText("P");
        bt_perfil.setPreferredSize(new java.awt.Dimension(64, 64));
        bt_perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_perfilMouseClicked(evt);
            }
        });

        bt_voltar.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        bt_voltar.setForeground(new java.awt.Color(255, 255, 255));
        bt_voltar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_voltar.setText("V");
        bt_voltar.setPreferredSize(new java.awt.Dimension(64, 64));
        bt_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_voltarMouseClicked(evt);
            }
        });

        bt_encontro.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        bt_encontro.setForeground(new java.awt.Color(255, 255, 255));
        bt_encontro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_encontro.setText("E");
        bt_encontro.setPreferredSize(new java.awt.Dimension(64, 64));
        bt_encontro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_encontroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(bt_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(bt_encontro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(bt_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_encontro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        painel_container.setBackground(new java.awt.Color(0, 0, 0));
        painel_container.setPreferredSize(new java.awt.Dimension(300, 550));

        imagem_list.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        imagem_list.setForeground(new java.awt.Color(255, 255, 255));
        imagem_list.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout painel_containerLayout = new javax.swing.GroupLayout(painel_container);
        painel_container.setLayout(painel_containerLayout);
        painel_containerLayout.setHorizontalGroup(
            painel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagem_list, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
        );
        painel_containerLayout.setVerticalGroup(
            painel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_containerLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(imagem_list, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );

        javax.swing.GroupLayout painel_fundoLayout = new javax.swing.GroupLayout(painel_fundo);
        painel_fundo.setLayout(painel_fundoLayout);
        painel_fundoLayout.setHorizontalGroup(
            painel_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
            .addComponent(painel_container, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
        );
        painel_fundoLayout.setVerticalGroup(
            painel_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_fundoLayout.createSequentialGroup()
                .addComponent(painel_container, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 460, Short.MAX_VALUE)
                .addComponent(painel_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 460, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1296, 728);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_voltarMouseClicked
        F_Login v = new F_Login();
        this.dispose();
        v.setVisible(true);
    }//GEN-LAST:event_bt_voltarMouseClicked

    private void bt_perfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_perfilMouseClicked
        F_Perfil p = new F_Perfil();
        this.dispose();
        p.setVisible(true);
    }//GEN-LAST:event_bt_perfilMouseClicked

    private void bt_encontroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_encontroMouseClicked
        /*
        F_encontro e = new F_encontro();
        this.dispose();
        e.setVisible(true);
        */
    }//GEN-LAST:event_bt_encontroMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
         Escolhas u = new Escolhas();

        switch (evt.getKeyCode()) {    
            case KeyEvent.VK_UP:
                System.out.println("Seta para cima pressionada");
                // passa
                break;
//            case KeyEvent.VK_DOWN:
//                System.out.println("Seta para baixo pressionada");
//                // volta
//                break;
            case KeyEvent.VK_LEFT:
                System.out.println("Seta para esquerda pressionada");
                // gostei
                this.gostei = 1;
                break;
            case KeyEvent.VK_RIGHT:
                System.out.println("Seta para direita pressionada");
                // amei
                this.amei = 1;
                break;
            default:
                break;
        }
        String[] dados = u.passa(this.id, this.atracao, this.nome, this.gostei, this.amei); // Call passa method
        try {
            this.id = Integer.parseInt(dados[0]);
            System.out.println(this.id);
            this.atracao = Integer.parseInt(dados[1]);
            System.out.println(this.atracao);
            this.nome = dados[2];
            System.out.println(this.nome);
            this.gostei = Integer.parseInt(dados[3]);
            System.out.println(this.gostei);
            this.amei = Integer.parseInt(dados[4]);
            System.out.println(this.amei);

        } catch (NumberFormatException e) {
            System.out.println("Erro ao converter dados: " + e.getMessage());
            // Handle the error as appropriate
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("Dados retornados não possuem o número esperado de elementos.");
            F_Login v = new F_Login();
            this.dispose();
            v.setVisible(true);
            // Handle the error as appropriate
        }
        imagem_list.setText(this.nome); // Update the UI with the name
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_documento;
    private javax.swing.JLabel bt_encontro;
    private javax.swing.JLabel bt_perfil;
    private javax.swing.JLabel bt_voltar;
    private javax.swing.JLabel imagem_list;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel painel_container;
    private javax.swing.JPanel painel_fundo;
    // End of variables declaration//GEN-END:variables
}
