package AsEscuras.Layout;

import AsEscuras.User.User_Cadastrar;
//import AsEscuras.User.User_edit;
import AsEscuras.User.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author GregoryGorzizadosSan
 */
public class F_Perfil extends javax.swing.JFrame {

    /**
     * Creates new form F_Cadastro_Cliente
     */
    public F_Perfil() {
        initComponents();
        carregar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        bg_documento = new javax.swing.ButtonGroup();
        painel_do_scrool = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        painel_fundo = new javax.swing.JPanel();
        bt_editar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        bt_perfil = new javax.swing.JLabel();
        bt_voltar1 = new javax.swing.JLabel();
        bt_home = new javax.swing.JLabel();
        painel_container = new javax.swing.JPanel();
        l_nome = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        l_senha = new javax.swing.JLabel();
        txt_senha = new javax.swing.JTextField();
        l_email = new javax.swing.JLabel();
        l_datebirt = new javax.swing.JLabel();
        txt_senha_confirm = new javax.swing.JTextField();
        l_localizacao = new javax.swing.JLabel();
        s_dia = new javax.swing.JSpinner();
        s_mes = new javax.swing.JSpinner();
        s_ano = new javax.swing.JSpinner();
        cb_localizacao = new javax.swing.JComboBox<>();
        l_genero = new javax.swing.JLabel();
        s_altura = new javax.swing.JSpinner();
        s_peso = new javax.swing.JSpinner();
        l_altura = new javax.swing.JLabel();
        l_peso = new javax.swing.JLabel();
        cb_fisico = new javax.swing.JComboBox<>();
        cb_cabelo = new javax.swing.JComboBox<>();
        l_fisico = new javax.swing.JLabel();
        l_cabelo = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        l_pele = new javax.swing.JLabel();
        cb_pele = new javax.swing.JComboBox<>();
        l_tatuagens = new javax.swing.JLabel();
        cb_certificacao = new javax.swing.JComboBox<>();
        l_certificacao = new javax.swing.JLabel();
        l_salario = new javax.swing.JLabel();
        cb_tatuagens = new javax.swing.JComboBox<>();
        cb_salario = new javax.swing.JComboBox<>();
        l_personalidade = new javax.swing.JLabel();
        cb_personalidade = new javax.swing.JComboBox<>();
        l_preferencias = new javax.swing.JLabel();
        l_pref_genero = new javax.swing.JLabel();
        cb_pref_genero = new javax.swing.JComboBox<>();
        l_pref_altura = new javax.swing.JLabel();
        cb_pref_altura = new javax.swing.JComboBox<>();
        l_pref_tatuagens = new javax.swing.JLabel();
        l_pref_cabelo = new javax.swing.JLabel();
        cb_pref_tatuagens = new javax.swing.JComboBox<>();
        cb_pref_cabelo = new javax.swing.JComboBox<>();
        l_pref_pele = new javax.swing.JLabel();
        cb_pref_pele = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        cb_Preto = new javax.swing.JCheckBox();
        cb_Loiro = new javax.swing.JCheckBox();
        cb_Ruivo = new javax.swing.JCheckBox();
        cb_Castanho = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        cb_claro = new javax.swing.JCheckBox();
        cb_cauca = new javax.swing.JCheckBox();
        cb_escuro = new javax.swing.JCheckBox();
        l_interesses = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        cb_viagens = new javax.swing.JCheckBox();
        cb_livros = new javax.swing.JCheckBox();
        cb_jogos = new javax.swing.JCheckBox();
        cb_artes = new javax.swing.JCheckBox();
        cb_animais = new javax.swing.JCheckBox();
        cb_natureza = new javax.swing.JCheckBox();
        cb_esporte = new javax.swing.JCheckBox();
        cb_causa = new javax.swing.JCheckBox();
        cb_gastronomia = new javax.swing.JCheckBox();
        cb_musica = new javax.swing.JCheckBox();
        l_preferencias1 = new javax.swing.JLabel();
        cb_generoBio1 = new javax.swing.JComboBox<>();

        jColorChooser1.setBackground(new java.awt.Color(0, 0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        painel_do_scrool.setBorder(null);
        painel_do_scrool.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        painel_do_scrool.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        painel_do_scrool.setAutoscrolls(true);
        painel_do_scrool.setPreferredSize(new java.awt.Dimension(360, 1200));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 1800));

        painel_fundo.setBackground(new java.awt.Color(0, 0, 0));
        painel_fundo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painel_fundo.setForeground(new java.awt.Color(255, 255, 255));
        painel_fundo.setPreferredSize(new java.awt.Dimension(360, 2000));

        bt_editar.setBackground(new java.awt.Color(51, 0, 0));
        bt_editar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        bt_editar.setForeground(new java.awt.Color(255, 255, 255));
        bt_editar.setText("Editar");
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(360, 100));

        bt_perfil.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        bt_perfil.setForeground(new java.awt.Color(255, 255, 255));
        bt_perfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_perfil.setText("P");
        bt_perfil.setPreferredSize(new java.awt.Dimension(64, 64));
        bt_perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_perfilMouseClicked(evt);
            }
        });

        bt_voltar1.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        bt_voltar1.setForeground(new java.awt.Color(255, 255, 255));
        bt_voltar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_voltar1.setText("V");
        bt_voltar1.setPreferredSize(new java.awt.Dimension(64, 64));
        bt_voltar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_voltar1MouseClicked(evt);
            }
        });

        bt_home.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        bt_home.setForeground(new java.awt.Color(255, 255, 255));
        bt_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_home.setText("H");
        bt_home.setPreferredSize(new java.awt.Dimension(64, 64));
        bt_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_homeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(bt_voltar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(bt_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_voltar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        painel_container.setBackground(new java.awt.Color(0, 0, 0));
        painel_container.setPreferredSize(new java.awt.Dimension(300, 2000));

        l_nome.setBackground(new java.awt.Color(255, 255, 255));
        l_nome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l_nome.setForeground(new java.awt.Color(255, 255, 255));
        l_nome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_nome.setText("Nome");
        l_nome.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txt_nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        l_senha.setBackground(new java.awt.Color(255, 255, 255));
        l_senha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l_senha.setForeground(new java.awt.Color(255, 255, 255));
        l_senha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_senha.setText("Senha");
        l_senha.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txt_senha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        l_email.setBackground(new java.awt.Color(255, 255, 255));
        l_email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l_email.setForeground(new java.awt.Color(255, 255, 255));
        l_email.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_email.setText("Email");
        l_email.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        l_datebirt.setBackground(new java.awt.Color(255, 255, 255));
        l_datebirt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l_datebirt.setForeground(new java.awt.Color(255, 255, 255));
        l_datebirt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_datebirt.setText("Data de nascimento");
        l_datebirt.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txt_senha_confirm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        l_localizacao.setBackground(new java.awt.Color(255, 255, 255));
        l_localizacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l_localizacao.setForeground(new java.awt.Color(255, 255, 255));
        l_localizacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_localizacao.setText("Localização");
        l_localizacao.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        s_dia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s_dia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));

        s_mes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s_mes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        s_ano.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s_ano.setModel(new javax.swing.SpinnerNumberModel(2006, 1944, 2006, 1));

        cb_localizacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_localizacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Porto Alegre" }));

        l_genero.setBackground(new java.awt.Color(255, 255, 255));
        l_genero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l_genero.setForeground(new java.awt.Color(255, 255, 255));
        l_genero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_genero.setText("Gênero biológico");
        l_genero.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        s_altura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s_altura.setModel(new javax.swing.SpinnerNumberModel(170, 100, 200, 10));

        s_peso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s_peso.setModel(new javax.swing.SpinnerNumberModel(60, 30, 500, 5));

        l_altura.setBackground(new java.awt.Color(255, 255, 255));
        l_altura.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l_altura.setForeground(new java.awt.Color(255, 255, 255));
        l_altura.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        l_altura.setText("Altura");
        l_altura.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        l_peso.setBackground(new java.awt.Color(255, 255, 255));
        l_peso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l_peso.setForeground(new java.awt.Color(255, 255, 255));
        l_peso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        l_peso.setText("Peso");
        l_peso.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        cb_fisico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_fisico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fora de forma", "Normal", "Em forma" }));

        cb_cabelo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_cabelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Preto", "Castanho", "Loiro", "Ruivo" }));

        l_fisico.setBackground(new java.awt.Color(255, 255, 255));
        l_fisico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l_fisico.setForeground(new java.awt.Color(255, 255, 255));
        l_fisico.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_fisico.setText("Forma Fisica:");
        l_fisico.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        l_cabelo.setBackground(new java.awt.Color(255, 255, 255));
        l_cabelo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l_cabelo.setForeground(new java.awt.Color(255, 255, 255));
        l_cabelo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_cabelo.setText("Cabelo Natural");
        l_cabelo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        l_pele.setBackground(new java.awt.Color(255, 255, 255));
        l_pele.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l_pele.setForeground(new java.awt.Color(255, 255, 255));
        l_pele.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_pele.setText("Tom de pele");
        l_pele.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        cb_pele.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_pele.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Claro", "Caucasiano", "Escuro" }));

        l_tatuagens.setBackground(new java.awt.Color(255, 255, 255));
        l_tatuagens.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l_tatuagens.setForeground(new java.awt.Color(255, 255, 255));
        l_tatuagens.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_tatuagens.setText("Tatuagens");
        l_tatuagens.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        cb_certificacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_certificacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim, ja possuo", "Sim, estou cursando ", "Não, mas pretendo fazer ", "Não tenho interesse" }));

        l_certificacao.setBackground(new java.awt.Color(255, 255, 255));
        l_certificacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l_certificacao.setForeground(new java.awt.Color(255, 255, 255));
        l_certificacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_certificacao.setText("Certificação profissional");
        l_certificacao.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        l_salario.setBackground(new java.awt.Color(255, 255, 255));
        l_salario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l_salario.setForeground(new java.awt.Color(255, 255, 255));
        l_salario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_salario.setText("Media Salarial");
        l_salario.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        cb_tatuagens.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_tatuagens.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Possuo", "Não Possuo" }));

        cb_salario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_salario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não informar", "1.000,00-5.000,00", "5.000,00-10.000,00", "+10.000,00" }));

        l_personalidade.setBackground(new java.awt.Color(255, 255, 255));
        l_personalidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l_personalidade.setForeground(new java.awt.Color(255, 255, 255));
        l_personalidade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_personalidade.setText("Personalidade");
        l_personalidade.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        cb_personalidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_personalidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Extrovertido, Entusiástico", "Líder, Determinado", "Analítico, Perfeccionista", "Calmo, Equilibrado" }));

        l_preferencias.setBackground(new java.awt.Color(255, 255, 255));
        l_preferencias.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        l_preferencias.setForeground(new java.awt.Color(255, 255, 255));
        l_preferencias.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_preferencias.setText("Preferencias");
        l_preferencias.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        l_pref_genero.setBackground(new java.awt.Color(255, 255, 255));
        l_pref_genero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l_pref_genero.setForeground(new java.awt.Color(255, 255, 255));
        l_pref_genero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_pref_genero.setText("Genero");
        l_pref_genero.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        cb_pref_genero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_pref_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));

        l_pref_altura.setBackground(new java.awt.Color(255, 255, 255));
        l_pref_altura.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l_pref_altura.setForeground(new java.awt.Color(255, 255, 255));
        l_pref_altura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_pref_altura.setText("Altura");
        l_pref_altura.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        cb_pref_altura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_pref_altura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menor", "Não me importo", "Maior" }));

        l_pref_tatuagens.setBackground(new java.awt.Color(255, 255, 255));
        l_pref_tatuagens.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l_pref_tatuagens.setForeground(new java.awt.Color(255, 255, 255));
        l_pref_tatuagens.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_pref_tatuagens.setText("Tatuagens");
        l_pref_tatuagens.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        l_pref_cabelo.setBackground(new java.awt.Color(255, 255, 255));
        l_pref_cabelo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l_pref_cabelo.setForeground(new java.awt.Color(255, 255, 255));
        l_pref_cabelo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_pref_cabelo.setText("Cor de cabelo Natural");
        l_pref_cabelo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        cb_pref_tatuagens.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_pref_tatuagens.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não me importo", "Prefiro sem" }));

        cb_pref_cabelo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_pref_cabelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Possuo Preferencias", "Não Possuo Preferencias" }));

        l_pref_pele.setBackground(new java.awt.Color(255, 255, 255));
        l_pref_pele.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l_pref_pele.setForeground(new java.awt.Color(255, 255, 255));
        l_pref_pele.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_pref_pele.setText("Tom de Pele");
        l_pref_pele.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        cb_pref_pele.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_pref_pele.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Possuo Preferencias", "Não Possuo Preferencias" }));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        cb_Preto.setBackground(new java.awt.Color(51, 51, 51));
        cb_Preto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_Preto.setForeground(new java.awt.Color(255, 255, 255));
        cb_Preto.setText("Preto");

        cb_Loiro.setBackground(new java.awt.Color(51, 51, 51));
        cb_Loiro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_Loiro.setForeground(new java.awt.Color(255, 255, 255));
        cb_Loiro.setText("Loiro");
        cb_Loiro.setToolTipText("");

        cb_Ruivo.setBackground(new java.awt.Color(51, 51, 51));
        cb_Ruivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_Ruivo.setForeground(new java.awt.Color(255, 255, 255));
        cb_Ruivo.setText("Ruivo");

        cb_Castanho.setBackground(new java.awt.Color(51, 51, 51));
        cb_Castanho.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_Castanho.setForeground(new java.awt.Color(255, 255, 255));
        cb_Castanho.setText("Castanho");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_Loiro)
                    .addComponent(cb_Preto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_Ruivo)
                    .addComponent(cb_Castanho))
                .addGap(50, 50, 50))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cb_Preto)
                    .addComponent(cb_Ruivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_Loiro)
                    .addComponent(cb_Castanho))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        cb_claro.setBackground(new java.awt.Color(51, 51, 51));
        cb_claro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_claro.setForeground(new java.awt.Color(255, 255, 255));
        cb_claro.setText("Claro");

        cb_cauca.setBackground(new java.awt.Color(51, 51, 51));
        cb_cauca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_cauca.setForeground(new java.awt.Color(255, 255, 255));
        cb_cauca.setText("Caucasiano");

        cb_escuro.setBackground(new java.awt.Color(51, 51, 51));
        cb_escuro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_escuro.setForeground(new java.awt.Color(255, 255, 255));
        cb_escuro.setText("Escuro");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(cb_claro)
                .addGap(18, 18, 18)
                .addComponent(cb_cauca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cb_escuro)
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_cauca)
                    .addComponent(cb_claro)
                    .addComponent(cb_escuro))
                .addGap(5, 5, 5))
        );

        l_interesses.setBackground(new java.awt.Color(255, 255, 255));
        l_interesses.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        l_interesses.setForeground(new java.awt.Color(255, 255, 255));
        l_interesses.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_interesses.setText("Interesses");
        l_interesses.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        cb_viagens.setBackground(new java.awt.Color(51, 51, 51));
        cb_viagens.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_viagens.setForeground(new java.awt.Color(255, 255, 255));
        cb_viagens.setText("Viagens");

        cb_livros.setBackground(new java.awt.Color(51, 51, 51));
        cb_livros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_livros.setForeground(new java.awt.Color(255, 255, 255));
        cb_livros.setText("Literatura/Historia");
        cb_livros.setToolTipText("");

        cb_jogos.setBackground(new java.awt.Color(51, 51, 51));
        cb_jogos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_jogos.setForeground(new java.awt.Color(255, 255, 255));
        cb_jogos.setText("Jogos/Vídeo Games");

        cb_artes.setBackground(new java.awt.Color(51, 51, 51));
        cb_artes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_artes.setForeground(new java.awt.Color(255, 255, 255));
        cb_artes.setText("Artes/Cinema");

        cb_animais.setBackground(new java.awt.Color(51, 51, 51));
        cb_animais.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_animais.setForeground(new java.awt.Color(255, 255, 255));
        cb_animais.setText("Animais/Pets");
        cb_animais.setToolTipText("");

        cb_natureza.setBackground(new java.awt.Color(51, 51, 51));
        cb_natureza.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_natureza.setForeground(new java.awt.Color(255, 255, 255));
        cb_natureza.setText("Natureza/Acampamento");

        cb_esporte.setBackground(new java.awt.Color(51, 51, 51));
        cb_esporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_esporte.setForeground(new java.awt.Color(255, 255, 255));
        cb_esporte.setText("Esportes/Academia");

        cb_causa.setBackground(new java.awt.Color(51, 51, 51));
        cb_causa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_causa.setForeground(new java.awt.Color(255, 255, 255));
        cb_causa.setText("Causas sociais/Politica");

        cb_gastronomia.setBackground(new java.awt.Color(51, 51, 51));
        cb_gastronomia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_gastronomia.setForeground(new java.awt.Color(255, 255, 255));
        cb_gastronomia.setText("Gastronomia/Cozinha");

        cb_musica.setBackground(new java.awt.Color(51, 51, 51));
        cb_musica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_musica.setForeground(new java.awt.Color(255, 255, 255));
        cb_musica.setText("Musica/Shows");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_viagens)
                    .addComponent(cb_livros)
                    .addComponent(cb_causa)
                    .addComponent(cb_animais)
                    .addComponent(cb_jogos)
                    .addComponent(cb_artes)
                    .addComponent(cb_natureza)
                    .addComponent(cb_esporte)
                    .addComponent(cb_gastronomia)
                    .addComponent(cb_musica))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(cb_viagens)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_livros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_causa)
                .addGap(12, 12, 12)
                .addComponent(cb_animais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_jogos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_artes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_natureza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_esporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_gastronomia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_musica)
                .addGap(10, 10, 10))
        );

        l_preferencias1.setBackground(new java.awt.Color(255, 255, 255));
        l_preferencias1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        l_preferencias1.setForeground(new java.awt.Color(255, 255, 255));
        l_preferencias1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_preferencias1.setText("Perfil");
        l_preferencias1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        cb_generoBio1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_generoBio1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));

        javax.swing.GroupLayout painel_containerLayout = new javax.swing.GroupLayout(painel_container);
        painel_container.setLayout(painel_containerLayout);
        painel_containerLayout.setHorizontalGroup(
            painel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_nome)
            .addComponent(txt_email)
            .addComponent(txt_senha)
            .addComponent(txt_senha_confirm)
            .addComponent(cb_localizacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cb_fisico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cb_cabelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cb_pele, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cb_tatuagens, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cb_certificacao, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cb_salario, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cb_personalidade, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_containerLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(painel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_altura, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_altura, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addGroup(painel_containerLayout.createSequentialGroup()
                .addGroup(painel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_containerLayout.createSequentialGroup()
                        .addComponent(l_nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                        .addComponent(l_preferencias1))
                    .addGroup(painel_containerLayout.createSequentialGroup()
                        .addGroup(painel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel_containerLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(s_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(s_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(s_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(l_email)
                            .addComponent(l_senha)
                            .addComponent(l_datebirt)
                            .addComponent(l_localizacao)
                            .addComponent(l_genero)
                            .addComponent(l_fisico)
                            .addComponent(l_cabelo)
                            .addComponent(l_pele)
                            .addComponent(l_tatuagens)
                            .addComponent(l_certificacao)
                            .addComponent(l_salario)
                            .addComponent(l_personalidade))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(painel_containerLayout.createSequentialGroup()
                .addGroup(painel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_containerLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l_preferencias))
                    .addGroup(painel_containerLayout.createSequentialGroup()
                        .addGroup(painel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_pref_genero)
                            .addComponent(l_pref_altura)
                            .addComponent(l_pref_tatuagens)
                            .addComponent(l_pref_cabelo)
                            .addComponent(l_pref_pele))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
            .addComponent(cb_pref_genero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cb_pref_tatuagens, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painel_containerLayout.createSequentialGroup()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(cb_pref_altura, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cb_pref_cabelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cb_pref_pele, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_containerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_interesses)
                .addContainerGap())
            .addGroup(painel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painel_containerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(cb_generoBio1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        painel_containerLayout.setVerticalGroup(
            painel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_containerLayout.createSequentialGroup()
                .addComponent(l_preferencias1)
                .addGap(0, 0, 0)
                .addComponent(l_nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_senha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_senha_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_datebirt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_localizacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_localizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(l_genero)
                .addGap(38, 38, 38)
                .addGroup(painel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_peso, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l_altura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s_peso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_fisico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_fisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_cabelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_cabelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_pele)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_pele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_tatuagens)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_tatuagens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_certificacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_certificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_salario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_personalidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_personalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(painel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_containerLayout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addComponent(jLabel24)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_containerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_interesses)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(l_preferencias)
                .addGap(9, 9, 9)
                .addComponent(l_pref_genero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_pref_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_pref_altura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_pref_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_pref_tatuagens)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_pref_tatuagens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_pref_cabelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_pref_cabelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(l_pref_pele)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_pref_pele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(painel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painel_containerLayout.createSequentialGroup()
                    .addGap(342, 342, 342)
                    .addComponent(cb_generoBio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1237, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout painel_fundoLayout = new javax.swing.GroupLayout(painel_fundo);
        painel_fundo.setLayout(painel_fundoLayout);
        painel_fundoLayout.setHorizontalGroup(
            painel_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_fundoLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(painel_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painel_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
        );
        painel_fundoLayout.setVerticalGroup(
            painel_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_fundoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(painel_container, javax.swing.GroupLayout.PREFERRED_SIZE, 1605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painel_fundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2000, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painel_fundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        painel_do_scrool.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_do_scrool, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_do_scrool, javax.swing.GroupLayout.DEFAULT_SIZE, 1800, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1296, 728);
    }// </editor-fold>//GEN-END:initComponents
    private void carregar(){
        Usuario u = new Usuario();  // Supondo que você tenha um objeto do tipo Usuario

        txt_email.setText(u.getEmail());
        txt_senha.setText(u.getSenha());
        txt_nome.setText(u.getNome());
        //cb_pref_cabelo.setSelectedItem("Porto Alegre");

        // Carregar os valores para os componentes de seleção
        s_dia.setValue(u.getDiaNascimento());
        s_mes.setValue(u.getMesNascimento());
        s_ano.setValue(u.getAnoNascimento());

        cb_localizacao.setSelectedIndex(u.getGeneroBio());
        s_altura.setValue(u.getAltura());
        s_peso.setValue(u.getPeso());
        cb_fisico.setSelectedIndex(u.getFormaFisica());
        cb_cabelo.setSelectedIndex(u.getCabeloNatural());
        cb_salario.setSelectedIndex(u.getSalario());

        // Preferências
        cb_pref_genero.setSelectedIndex(u.getIntGeneroBio());
        cb_pref_altura.setSelectedIndex(u.getIntAltura());
        
        if (u.getCertificaProfi() == 0){cb_certificacao.setSelectedIndex(3);}
        if (u.getIntTatuagens()== 0){cb_pref_tatuagens.setSelectedItem("Prefiro com");}
        if (u.getTatuagens()== 0){cb_tatuagens.setSelectedItem("Não possuo");}
        if (u.getIntCabeloNatural()== 1){
            cb_pref_cabelo.setSelectedItem("Possuo Preferências");
            if (u.getPreto()== 1){cb_Preto.setSelected(true);}
            if (u.getCastanho()== 1){cb_Castanho.setSelected(true);}
            if (u.getLoiro()== 1){cb_Loiro.setSelected(true);}
            if (u.getRuivo()== 1){cb_Ruivo.setSelected(true);}
        }
        
    }
    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
        try {  
            String email = txt_email.getText();
            String senha = txt_senha.getText();
            String senhaConfirm = txt_senha_confirm.getText();
            String nome = txt_nome.getText();
            int diaNascimento = (Integer) s_dia.getValue();
            int mesNascimento = (Integer) s_mes.getValue();
            int anoNascimento = (Integer) s_ano.getValue();
            String localizacao = cb_localizacao.getName();         
            int generoBio = cb_localizacao.getSelectedIndex();
            int altura = (Integer) s_altura.getValue();
            int peso = (Integer) s_peso.getValue();         
            int formaFisica = cb_fisico.getSelectedIndex();
            int cabeloNatural = cb_cabelo.getSelectedIndex();
            int pele = cb_pele.getSelectedIndex();
            int tatuagens = cb_tatuagens.getSelectedItem().equals("Possuo") ? 1 : 0; // Convertendo para int
            int salario = cb_salario.getSelectedIndex();
            int certificacao = cb_certificacao.getSelectedIndex();
            int personalidade = cb_personalidade.getSelectedIndex();

            int intGeneroBio = cb_pref_genero.getSelectedIndex();
            int intAltura = cb_pref_altura.getSelectedIndex();
            int intTatuagens = cb_pref_tatuagens.getSelectedItem().equals("Prefiro sem") ? 1 : 0; // Convertendo para int
            int intCabeloNatural = cb_pref_cabelo.getSelectedItem().equals("Possuo Preferências") ? 1 : 0; // Convertendo para int
            int preto = cb_Preto.isSelected() ? 1 : 0; // Convertendo para int
            int castanho = cb_Castanho.isSelected() ? 1 : 0; // Convertendo para int
            int loiro = cb_Loiro.isSelected() ? 1 : 0; // Convertendo para int
            int ruivo = cb_Ruivo.isSelected() ? 1 : 0; // Convertendo para int
            int intPele = cb_pref_pele.getSelectedItem().equals("Possuo Preferências") ? 1 : 0; // Convertendo para int
            int claro = cb_claro.isSelected() ? 1 : 0; // Convertendo para int
            int cauca = cb_cauca.isSelected() ? 1 : 0; // Convertendo para int
            int escuro = cb_escuro.isSelected() ? 1 : 0; // Convertendo para int

            int viagens = cb_viagens.isSelected() ? 1 : 0; // Convertendo para int
            int musica = cb_musica.isSelected() ? 1 : 0; // Convertendo para int
            int gastronomia = cb_gastronomia.isSelected() ? 1 : 0; // Convertendo para int
            int livros = cb_livros.isSelected() ? 1 : 0; // Convertendo para int
            int esportes = cb_esporte.isSelected() ? 1 : 0; // Convertendo para int
            int natureza = cb_natureza.isSelected() ? 1 : 0; // Convertendo para int
            int artes = cb_artes.isSelected() ? 1 : 0; // Convertendo para int
            int jogos = cb_jogos.isSelected() ? 1 : 0; // Convertendo para int
            int animais = cb_animais.isSelected() ? 1 : 0; // Convertendo para int
            int causa = cb_causa.isSelected() ? 1 : 0; // Convertendo para int

            if (nome.trim().isEmpty()) {
                mostrarMensagem("O nome não pode estar vazio!");
                return;
            }

            if (!isEmailValido(email)) {
                mostrarMensagem("Email inválido!");
                return;
            }

            if (!isSenhaValida(senha, senhaConfirm)) {
                return; // Note: you might want to add a message here
            }

            if (localizacao.trim().isEmpty()) {
                mostrarMensagem("A localização não pode estar vazia!");
                return;
            }

            int certificaProfi = isCertificacaoValida(certificacao);

            // Validate cabelo preferences
            if (intCabeloNatural == 1 && preto == 0 && castanho == 0 && loiro == 0 && ruivo == 0 ) {
                mostrarMensagem("Escolha sua preferência de cor de cabelo!");
                return;
            }  
            Usuario u = new Usuario();

            int idade = u.getIdade();
            int imc = u.getImc();
            int id = u.getId();

            // Register the user
//            User_edit user = new User_edit();
//            user.Editar(id, email, senha, nome, diaNascimento, 
//                mesNascimento, anoNascimento, idade, localizacao, 
//                generoBio, altura, peso, formaFisica, 
//                imc, cabeloNatural, pele, tatuagens, 
//                salario, certificaProfi, personalidade, intGeneroBio, 
//                intAltura, intTatuagens, intCabeloNatural, preto, 
//                castanho, loiro, ruivo, intPele, 
//                escuro, cauca, claro, viagens, 
//                musica, gastronomia, livros, esportes, 
//                natureza, artes, jogos, animais, 
//                causa);
            // Navigate to home after successful registration
            F_Home h = new F_Home();
            this.dispose();
            h.setVisible(true);

        } catch (Exception e) {
            System.out.println("Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_bt_editarActionPerformed

    private void bt_perfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_perfilMouseClicked
        F_Login p = new F_Login();
        this.dispose();
        p.setVisible(true);
    }//GEN-LAST:event_bt_perfilMouseClicked

    private void bt_voltar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_voltar1MouseClicked
        F_Login v = new F_Login();
        this.dispose();
        v.setVisible(true);
    }//GEN-LAST:event_bt_voltar1MouseClicked

    private void bt_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_homeMouseClicked
        F_Login h = new F_Login();
        this.dispose();
        h.setVisible(true);
    }//GEN-LAST:event_bt_homeMouseClicked

    private boolean isEmailValido(String email) {
        return email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$");
    }

    private boolean isSenhaValida(String senha, String senhaConfirm) {
        if (senha.length() < 6 || senhaConfirm.length() < 6) {
            mostrarMensagem("A senha deve ter no minimo 6 caracteres!");
            return false;
        }
        if (!senha.equals(senhaConfirm)) {
            mostrarMensagem("As senhas não coincidem!");
            return false;
        }
        return true;
    }

    private int isCertificacaoValida(int certificacao) {
        if (certificacao == 3){
            return 0;
        }else{
            return 1;
        }
    }

    private void mostrarMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_documento;
    private javax.swing.JButton bt_editar;
    private javax.swing.JLabel bt_home;
    private javax.swing.JLabel bt_perfil;
    private javax.swing.JLabel bt_voltar1;
    private javax.swing.JCheckBox cb_Castanho;
    private javax.swing.JCheckBox cb_Loiro;
    private javax.swing.JCheckBox cb_Preto;
    private javax.swing.JCheckBox cb_Ruivo;
    private javax.swing.JCheckBox cb_animais;
    private javax.swing.JCheckBox cb_artes;
    private javax.swing.JComboBox<String> cb_cabelo;
    private javax.swing.JCheckBox cb_cauca;
    private javax.swing.JCheckBox cb_causa;
    private javax.swing.JComboBox<String> cb_certificacao;
    private javax.swing.JCheckBox cb_claro;
    private javax.swing.JCheckBox cb_escuro;
    private javax.swing.JCheckBox cb_esporte;
    private javax.swing.JComboBox<String> cb_fisico;
    private javax.swing.JCheckBox cb_gastronomia;
    private javax.swing.JComboBox<String> cb_generoBio1;
    private javax.swing.JCheckBox cb_jogos;
    private javax.swing.JCheckBox cb_livros;
    private javax.swing.JComboBox<String> cb_localizacao;
    private javax.swing.JCheckBox cb_musica;
    private javax.swing.JCheckBox cb_natureza;
    private javax.swing.JComboBox<String> cb_pele;
    private javax.swing.JComboBox<String> cb_personalidade;
    private javax.swing.JComboBox<String> cb_pref_altura;
    private javax.swing.JComboBox<String> cb_pref_cabelo;
    private javax.swing.JComboBox<String> cb_pref_genero;
    private javax.swing.JComboBox<String> cb_pref_pele;
    private javax.swing.JComboBox<String> cb_pref_tatuagens;
    private javax.swing.JComboBox<String> cb_salario;
    private javax.swing.JComboBox<String> cb_tatuagens;
    private javax.swing.JCheckBox cb_viagens;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel l_altura;
    private javax.swing.JLabel l_cabelo;
    private javax.swing.JLabel l_certificacao;
    private javax.swing.JLabel l_datebirt;
    private javax.swing.JLabel l_email;
    private javax.swing.JLabel l_fisico;
    private javax.swing.JLabel l_genero;
    private javax.swing.JLabel l_interesses;
    private javax.swing.JLabel l_localizacao;
    private javax.swing.JLabel l_nome;
    private javax.swing.JLabel l_pele;
    private javax.swing.JLabel l_personalidade;
    private javax.swing.JLabel l_peso;
    private javax.swing.JLabel l_pref_altura;
    private javax.swing.JLabel l_pref_cabelo;
    private javax.swing.JLabel l_pref_genero;
    private javax.swing.JLabel l_pref_pele;
    private javax.swing.JLabel l_pref_tatuagens;
    private javax.swing.JLabel l_preferencias;
    private javax.swing.JLabel l_preferencias1;
    private javax.swing.JLabel l_salario;
    private javax.swing.JLabel l_senha;
    private javax.swing.JLabel l_tatuagens;
    private javax.swing.JPanel painel_container;
    private javax.swing.JScrollPane painel_do_scrool;
    private javax.swing.JPanel painel_fundo;
    private javax.swing.JSpinner s_altura;
    private javax.swing.JSpinner s_ano;
    private javax.swing.JSpinner s_dia;
    private javax.swing.JSpinner s_mes;
    private javax.swing.JSpinner s_peso;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_senha;
    private javax.swing.JTextField txt_senha_confirm;
    // End of variables declaration//GEN-END:variables
}
